### ISSUE TITLE
Docker 1.5.0

### ISSUE THREAD

**Issue by pbelmann** [moul/travis-docker#4] opened 2015-02-13 13:03 UTC
Have you tried to run your scripts with Docker 1.5.0. It does not work with my travis.yml.

**Comment by moul** [comment] 2015-02-13 13:56
Not tried yet, do you have a trace of the error ?

**Comment by pbelmann** [comment] 2015-02-13 14:12
It is actually not an error. It seems that travis cannot setup lxc-docker. So that is the last output for one build:

Setting up cgroup-lite (1.1.5) ...
invoke-rc.d: policy-rc.d denied execution of start.
Setting up cloud-utils (0.25-0ubuntu5.1) ...
Setting up debootstrap (1.0.40~ubuntu0.7) ...
Setting up lxc-docker-1.5.0 (1.5.0) ...

**Comment by moul** [comment] 2015-02-13 15:26
Yes, I've the same problem here :/
https://travis-ci.org/pathwar/level-captcha/builds/50644570#L374

Need more investigation

**Comment by mtucker6784** [comment] 2015-02-17 22:43
I'm setting up a docker-pinry package and I receive the same results as above on both a 12.02 and 14.04 box.

The following extra packages will be installed:
  lxc-docker-1.5.0
The following NEW packages will be installed:
  lxc-docker lxc-docker-1.5.0
0 upgraded, 2 newly installed, 0 to remove and 109 not upgraded.
Need to get 4635 kB of archives.
After this operation, 15.1 MB of additional disk space will be used.
Get:1 https://get.docker.com/ubuntu/ docker/main lxc-docker-1.5.0 amd64 1.5.0 [4
Get:2 https://get.docker.com/ubuntu/ docker/main lxc-docker amd64 1.5.0 [2092 B]
Fetched 4635 kB in 8s (573 kB/s)
Selecting previously unselected package lxc-docker-1.5.0.
(Reading database ... 84493 files and directories currently installed.)
Preparing to unpack .../lxc-docker-1.5.0_1.5.0_amd64.deb ...
Unpacking lxc-docker-1.5.0 (1.5.0) ...
Selecting previously unselected package lxc-docker.
Preparing to unpack .../lxc-docker_1.5.0_amd64.deb ...
Unpacking lxc-docker (1.5.0) ...
Processing triggers for man-db (2.6.7.1-1) ...
Setting up lxc-docker-1.5.0 (1.5.0) ...

And that's all that happens. Been idling there for the last hour. Stumbled upon this post, hoping to see if I'm missing something or there is a quick resolution I can use. Thanks!

**Comment by moul** [comment] 2015-02-18 23:35
No I'm sorry, but this docker 1.5.0 upgrade broke everything, we need to find the cause to fix it or at least a way to force the version of docker to be installed, what are you both thinking about this ?

**Comment by ir4y** [comment] 2015-02-20 15:23
Hello.
I have the same issue. I fixed it by manualy selecting docker version.

```
install:
  - wget http://get.docker.io/ubuntu/pool/main/l/lxc-docker-1.4.1/lxc-docker-1.4.1_1.4.1_amd64.deb
  - sudo dpkg -i lxc-docker-1.4.1_1.4.1_amd64.deb
  - sudo apt-get -fy install
  - sudo apt-get -y install cgroup-lite
```

May be it will be usefull fore somebody.

**Comment by moul** [comment] 2015-02-20 15:48
@ir4y thank you !
This workaround is perfect to unblock the situation, I'm updating the sources right now

**Comment by moul** [comment] 2015-02-20 16:00
It works (see https://travis-ci.org/moul/travis-docker/builds/51526951)

Thanks again, I'm closing this issue and creating a new one for the docker upgrade

**Closed as completed by moul** 2015-02-20 16:00 UTC
Labels: bug, help wanted
